//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.NRMWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nrm.ws.integ.neps.ag.com/wsdl/NrmSoapServices", ConfigurationName="NRMWebService.NrmServiceInterface")]
    public interface NrmServiceInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nrm.ws.integ.neps.ag.com/wsdl/NrmSoapServices/BOQ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string BOQ(string jobId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nrm.ws.integ.neps.ag.com/wsdl/NrmSoapServices/CreateProject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string CreateProject(string schemeName, string description, string jobId, string jobState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nrm.ws.integ.neps.ag.com/wsdl/NrmSoapServices/DeleteProject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string DeleteProject(string jobId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nrm.ws.integ.neps.ag.com/wsdl/NrmSoapServices/FindProject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        WebView.NRMWebService.NrmProject FindProject(string jobId);
        
        // CODEGEN: Parameter 'result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://nrm.ws.integ.neps.ag.com/wsdl/NrmSoapServices/GetIspEquipmentFromJobId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        WebView.NRMWebService.GetIspEquipmentFromJobIdResponse GetIspEquipmentFromJobId(WebView.NRMWebService.GetIspEquipmentFromJobIdRequest request);
        
        // CODEGEN: Parameter 'result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://nrm.ws.integ.neps.ag.com/wsdl/NrmSoapServices/ListProjects", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        WebView.NRMWebService.ListProjectsResponse ListProjects(WebView.NRMWebService.ListProjectsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nrm.ws.integ.neps.ag.com/wsdl/NrmSoapServices/TestConnect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string TestConnect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nrm.ws.integ.neps.ag.com/wsdl/NrmSoapServices/UpdateProject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string UpdateProject(string schemeName, string description, string jobId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrm.ws.integ.neps.ag.com/types/NrmSoapServices")]
    public partial class NrmProject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private long idField;
        
        private string jobIdField;
        
        private string jobStateField;
        
        private string schemeNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string jobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
                this.RaisePropertyChanged("jobId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string jobState {
            get {
                return this.jobStateField;
            }
            set {
                this.jobStateField = value;
                this.RaisePropertyChanged("jobState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string schemeName {
            get {
                return this.schemeNameField;
            }
            set {
                this.schemeNameField = value;
                this.RaisePropertyChanged("schemeName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nrm.ws.integ.neps.ag.com/types/NrmSoapServices")]
    public partial class NetworkElementType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string idField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetIspEquipmentFromJobId", WrapperNamespace="http://nrm.ws.integ.neps.ag.com/wsdl/NrmSoapServices", IsWrapped=true)]
    public partial class GetIspEquipmentFromJobIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string jobId;
        
        public GetIspEquipmentFromJobIdRequest() {
        }
        
        public GetIspEquipmentFromJobIdRequest(string jobId) {
            this.jobId = jobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetIspEquipmentFromJobIdResponse", WrapperNamespace="http://nrm.ws.integ.neps.ag.com/wsdl/NrmSoapServices", IsWrapped=true)]
    public partial class GetIspEquipmentFromJobIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WebView.NRMWebService.NetworkElementType[] result;
        
        public GetIspEquipmentFromJobIdResponse() {
        }
        
        public GetIspEquipmentFromJobIdResponse(WebView.NRMWebService.NetworkElementType[] result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListProjects", WrapperNamespace="http://nrm.ws.integ.neps.ag.com/wsdl/NrmSoapServices", IsWrapped=true)]
    public partial class ListProjectsRequest {
        
        public ListProjectsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListProjectsResponse", WrapperNamespace="http://nrm.ws.integ.neps.ag.com/wsdl/NrmSoapServices", IsWrapped=true)]
    public partial class ListProjectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WebView.NRMWebService.NrmProject[] result;
        
        public ListProjectsResponse() {
        }
        
        public ListProjectsResponse(WebView.NRMWebService.NrmProject[] result) {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NrmServiceInterfaceChannel : WebView.NRMWebService.NrmServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NrmServiceInterfaceClient : System.ServiceModel.ClientBase<WebView.NRMWebService.NrmServiceInterface>, WebView.NRMWebService.NrmServiceInterface {
        
        public NrmServiceInterfaceClient() {
        }
        
        public NrmServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NrmServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NrmServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NrmServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string BOQ(string jobId) {
            return base.Channel.BOQ(jobId);
        }
        
        public string CreateProject(string schemeName, string description, string jobId, string jobState) {
            return base.Channel.CreateProject(schemeName, description, jobId, jobState);
        }
        
        public string DeleteProject(string jobId) {
            return base.Channel.DeleteProject(jobId);
        }
        
        public WebView.NRMWebService.NrmProject FindProject(string jobId) {
            return base.Channel.FindProject(jobId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebView.NRMWebService.GetIspEquipmentFromJobIdResponse WebView.NRMWebService.NrmServiceInterface.GetIspEquipmentFromJobId(WebView.NRMWebService.GetIspEquipmentFromJobIdRequest request) {
            return base.Channel.GetIspEquipmentFromJobId(request);
        }
        
        public WebView.NRMWebService.NetworkElementType[] GetIspEquipmentFromJobId(string jobId) {
            WebView.NRMWebService.GetIspEquipmentFromJobIdRequest inValue = new WebView.NRMWebService.GetIspEquipmentFromJobIdRequest();
            inValue.jobId = jobId;
            WebView.NRMWebService.GetIspEquipmentFromJobIdResponse retVal = ((WebView.NRMWebService.NrmServiceInterface)(this)).GetIspEquipmentFromJobId(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebView.NRMWebService.ListProjectsResponse WebView.NRMWebService.NrmServiceInterface.ListProjects(WebView.NRMWebService.ListProjectsRequest request) {
            return base.Channel.ListProjects(request);
        }
        
        public WebView.NRMWebService.NrmProject[] ListProjects() {
            WebView.NRMWebService.ListProjectsRequest inValue = new WebView.NRMWebService.ListProjectsRequest();
            WebView.NRMWebService.ListProjectsResponse retVal = ((WebView.NRMWebService.NrmServiceInterface)(this)).ListProjects(inValue);
            return retVal.result;
        }
        
        public string TestConnect() {
            return base.Channel.TestConnect();
        }
        
        public string UpdateProject(string schemeName, string description, string jobId) {
            return base.Channel.UpdateProject(schemeName, description, jobId);
        }
    }
}
