//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.ISPHandoverServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.integ.neps.ag.com/neps_procman_isp/", ConfigurationName="ISPHandoverServices.neps_procman_isp")]
    public interface neps_procman_isp {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.integ.neps.ag.com/neps_procman_isp/CreateProcess", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="processId")]
        int CreateProcess(out WebView.ISPHandoverServices.Error_ISP error, string nepsJobId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.integ.neps.ag.com/neps_procman_isp/QueryProcessStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="processStatus")]
        string QueryProcessStatus(out WebView.ISPHandoverServices.Error_ISP error, int processId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.integ.neps.ag.com/neps_procman_isp/")]
    public partial class Error_ISP : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface neps_procman_ispChannel : WebView.ISPHandoverServices.neps_procman_isp, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class neps_procman_ispClient : System.ServiceModel.ClientBase<WebView.ISPHandoverServices.neps_procman_isp>, WebView.ISPHandoverServices.neps_procman_isp {
        
        public neps_procman_ispClient() {
        }
        
        public neps_procman_ispClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public neps_procman_ispClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public neps_procman_ispClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public neps_procman_ispClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }

        public int CreateProcess(out WebView.ISPHandoverServices.Error_ISP error, string nepsJobId)
        {
            return base.Channel.CreateProcess(out error, nepsJobId);
        }

        public string QueryProcessStatus(out WebView.ISPHandoverServices.Error_ISP error, int processId)
        {
            return base.Channel.QueryProcessStatus(out error, processId);
        }
    }
}
