//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.NEPS_NIS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nis.tm.com/", ConfigurationName="NEPS_NIS.TM_NEPSManagementAPI")]
    public interface TM_NEPSManagementAPI {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebView.NEPS_NIS.createFrameContainersResponse createFrameContainers(WebView.NEPS_NIS.createFrameContainersRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebView.NEPS_NIS.createFrameUnitsResponse createFrameUnits(WebView.NEPS_NIS.createFrameUnitsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebView.NEPS_NIS.createServiceBoundaryResponse createServiceBoundary(WebView.NEPS_NIS.createServiceBoundaryRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebView.NEPS_NIS.createNetworkElementResponse createNetworkElement(WebView.NEPS_NIS.createNetworkElementRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebView.NEPS_NIS.createCardResponse createCard(WebView.NEPS_NIS.createCardRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebView.NEPS_NIS.createCableSheathResponse createCableSheath(WebView.NEPS_NIS.createCableSheathRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebView.NEPS_NIS.dataMatchingUpdateResponse dataMatchingUpdate(WebView.NEPS_NIS.dataMatchingUpdateRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebView.NEPS_NIS.dataMatchingQueryResponse dataMatchingQuery(WebView.NEPS_NIS.dataMatchingQueryRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebView.NEPS_NIS.updateDPAdressesResponse updateDPAdresses(WebView.NEPS_NIS.updateDPAdressesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nis.tm.com/")]
    public partial class createFCReply : commonResponse {
        
        private string fracIdField;
        
        private string g3eFidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fracId {
            get {
                return this.fracIdField;
            }
            set {
                this.fracIdField = value;
                this.RaisePropertyChanged("fracId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string g3eFid {
            get {
                return this.g3eFidField;
            }
            set {
                this.g3eFidField = value;
                this.RaisePropertyChanged("g3eFid");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(createFCReply))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(dataMatchingQueryReply))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(createCSReply))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(createNEReply))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(createFUReply))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(createCardReply))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nis.tm.com/")]
    public partial class commonResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
                this.RaisePropertyChanged("errorMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nis.tm.com/")]
    public partial class attribute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nis.tm.com/")]
    public partial class dataMatchingQueryReply : commonResponse {
        
        private attribute[] attributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public attribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nis.tm.com/")]
    public partial class createCSReply : commonResponse {
        
        private decimal cabsIdField;
        
        private bool cabsIdFieldSpecified;
        
        private string g3eFidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal cabsId {
            get {
                return this.cabsIdField;
            }
            set {
                this.cabsIdField = value;
                this.RaisePropertyChanged("cabsId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cabsIdSpecified {
            get {
                return this.cabsIdFieldSpecified;
            }
            set {
                this.cabsIdFieldSpecified = value;
                this.RaisePropertyChanged("cabsIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string g3eFid {
            get {
                return this.g3eFidField;
            }
            set {
                this.g3eFidField = value;
                this.RaisePropertyChanged("g3eFid");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nis.tm.com/")]
    public partial class createNEReply : commonResponse {
        
        private decimal equp_IdField;
        
        private bool equp_IdFieldSpecified;
        
        private string g3e_FidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal equp_Id {
            get {
                return this.equp_IdField;
            }
            set {
                this.equp_IdField = value;
                this.RaisePropertyChanged("equp_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool equp_IdSpecified {
            get {
                return this.equp_IdFieldSpecified;
            }
            set {
                this.equp_IdFieldSpecified = value;
                this.RaisePropertyChanged("equp_IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string g3e_Fid {
            get {
                return this.g3e_FidField;
            }
            set {
                this.g3e_FidField = value;
                this.RaisePropertyChanged("g3e_Fid");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nis.tm.com/")]
    public partial class createFUReply : commonResponse {
        
        private decimal frauIdField;
        
        private bool frauIdFieldSpecified;
        
        private string g3eFidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal frauId {
            get {
                return this.frauIdField;
            }
            set {
                this.frauIdField = value;
                this.RaisePropertyChanged("frauId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool frauIdSpecified {
            get {
                return this.frauIdFieldSpecified;
            }
            set {
                this.frauIdFieldSpecified = value;
                this.RaisePropertyChanged("frauIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string g3eFid {
            get {
                return this.g3eFidField;
            }
            set {
                this.g3eFidField = value;
                this.RaisePropertyChanged("g3eFid");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nis.tm.com/")]
    public partial class createCardReply : commonResponse {
        
        private string cardIdField;
        
        private string g3eFidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cardId {
            get {
                return this.cardIdField;
            }
            set {
                this.cardIdField = value;
                this.RaisePropertyChanged("cardId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string g3eFid {
            get {
                return this.g3eFidField;
            }
            set {
                this.g3eFidField = value;
                this.RaisePropertyChanged("g3eFid");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFrameContainers", WrapperNamespace="http://nis.tm.com/", IsWrapped=true)]
    public partial class createFrameContainersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string locnTtname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string franName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string index;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string locationDetail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string areaCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string areaDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string areaAreaCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string areaAretCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string g3e_fid;
        
        public createFrameContainersRequest() {
        }
        
        public createFrameContainersRequest(string locnTtname, string franName, string index, string status, string locationDetail, string areaCode, string areaDescription, string areaAreaCode, string areaAretCode, string g3e_fid) {
            this.locnTtname = locnTtname;
            this.franName = franName;
            this.index = index;
            this.status = status;
            this.locationDetail = locationDetail;
            this.areaCode = areaCode;
            this.areaDescription = areaDescription;
            this.areaAreaCode = areaAreaCode;
            this.areaAretCode = areaAretCode;
            this.g3e_fid = g3e_fid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFrameContainersResponse", WrapperNamespace="http://nis.tm.com/", IsWrapped=true)]
    public partial class createFrameContainersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebView.NEPS_NIS.createFCReply @return;
        
        public createFrameContainersResponse() {
        }
        
        public createFrameContainersResponse(WebView.NEPS_NIS.createFCReply @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFrameUnits", WrapperNamespace="http://nis.tm.com/", IsWrapped=true)]
    public partial class createFrameUnitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal fracId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string frauPosition;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string frauName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal frauDistance;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fuptManrAbbreaviation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string terminationType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string productType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal countPair;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string g3e_fid;
        
        public createFrameUnitsRequest() {
        }
        
        public createFrameUnitsRequest(decimal fracId, string frauPosition, string frauName, decimal frauDistance, string fuptManrAbbreaviation, string terminationType, string productType, decimal countPair, string g3e_fid) {
            this.fracId = fracId;
            this.frauPosition = frauPosition;
            this.frauName = frauName;
            this.frauDistance = frauDistance;
            this.fuptManrAbbreaviation = fuptManrAbbreaviation;
            this.terminationType = terminationType;
            this.productType = productType;
            this.countPair = countPair;
            this.g3e_fid = g3e_fid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFrameUnitsResponse", WrapperNamespace="http://nis.tm.com/", IsWrapped=true)]
    public partial class createFrameUnitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebView.NEPS_NIS.createFUReply @return;
        
        public createFrameUnitsResponse() {
        }
        
        public createFrameUnitsResponse(WebView.NEPS_NIS.createFUReply @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createServiceBoundary", WrapperNamespace="http://nis.tm.com/", IsWrapped=true)]
    public partial class createServiceBoundaryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string g3e_fid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string frac_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string streetNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string streetType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string streetName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string suburb;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string city;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string statAbbreviation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string poscCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string country;
        
        public createServiceBoundaryRequest() {
        }
        
        public createServiceBoundaryRequest(string g3e_fid, string frac_id, string field1, string field2, string streetNumber, string streetType, string streetName, string suburb, string city, string statAbbreviation, string poscCode, string country) {
            this.g3e_fid = g3e_fid;
            this.frac_id = frac_id;
            this.field1 = field1;
            this.field2 = field2;
            this.streetNumber = streetNumber;
            this.streetType = streetType;
            this.streetName = streetName;
            this.suburb = suburb;
            this.city = city;
            this.statAbbreviation = statAbbreviation;
            this.poscCode = poscCode;
            this.country = country;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createServiceBoundaryResponse", WrapperNamespace="http://nis.tm.com/", IsWrapped=true)]
    public partial class createServiceBoundaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebView.NEPS_NIS.commonResponse @return;
        
        public createServiceBoundaryResponse() {
        }
        
        public createServiceBoundaryResponse(WebView.NEPS_NIS.commonResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createNetworkElement", WrapperNamespace="http://nis.tm.com/", IsWrapped=true)]
    public partial class createNetworkElementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equpLocnTtname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equpEqutAbbreviation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equpIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string locnDetail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string areaCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string areaDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string areaAretCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string areaAreaCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equpStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equpManrAbbreviation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equpEqumModel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string g3e_fid;
        
        public createNetworkElementRequest() {
        }
        
        public createNetworkElementRequest(string equpLocnTtname, string equpEqutAbbreviation, string equpIndex, string locnDetail, string areaCode, string areaDescription, string areaAretCode, string areaAreaCode, string equpStatus, string equpManrAbbreviation, string equpEqumModel, string g3e_fid) {
            this.equpLocnTtname = equpLocnTtname;
            this.equpEqutAbbreviation = equpEqutAbbreviation;
            this.equpIndex = equpIndex;
            this.locnDetail = locnDetail;
            this.areaCode = areaCode;
            this.areaDescription = areaDescription;
            this.areaAretCode = areaAretCode;
            this.areaAreaCode = areaAreaCode;
            this.equpStatus = equpStatus;
            this.equpManrAbbreviation = equpManrAbbreviation;
            this.equpEqumModel = equpEqumModel;
            this.g3e_fid = g3e_fid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createNetworkElementResponse", WrapperNamespace="http://nis.tm.com/", IsWrapped=true)]
    public partial class createNetworkElementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebView.NEPS_NIS.createNEReply @return;
        
        public createNetworkElementResponse() {
        }
        
        public createNetworkElementResponse(WebView.NEPS_NIS.createNEReply @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createCard", WrapperNamespace="http://nis.tm.com/", IsWrapped=true)]
    public partial class createCardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equpId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardSlot;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardModel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardSerial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal cardCountPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string portStartNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string g3e_fid;
        
        public createCardRequest() {
        }
        
        public createCardRequest(string equpId, string cardSlot, string cardName, string cardModel, string cardStatus, string cardSerial, decimal cardCountPort, string portStartNum, string g3e_fid) {
            this.equpId = equpId;
            this.cardSlot = cardSlot;
            this.cardName = cardName;
            this.cardModel = cardModel;
            this.cardStatus = cardStatus;
            this.cardSerial = cardSerial;
            this.cardCountPort = cardCountPort;
            this.portStartNum = portStartNum;
            this.g3e_fid = g3e_fid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createCardResponse", WrapperNamespace="http://nis.tm.com/", IsWrapped=true)]
    public partial class createCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebView.NEPS_NIS.createCardReply @return;
        
        public createCardResponse() {
        }
        
        public createCardResponse(WebView.NEPS_NIS.createCardReply @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createCableSheath", WrapperNamespace="http://nis.tm.com/", IsWrapped=true)]
    public partial class createCableSheathRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cabsName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cabsCastType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cabsStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string csptProductName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal minNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal maxNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal pairCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string locationA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string locationB;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string g3e_fid;
        
        public createCableSheathRequest() {
        }
        
        public createCableSheathRequest(string cabsName, string cabsCastType, string cabsStatus, string csptProductName, decimal minNumber, decimal maxNumber, decimal pairCount, string locationA, string locationB, string g3e_fid) {
            this.cabsName = cabsName;
            this.cabsCastType = cabsCastType;
            this.cabsStatus = cabsStatus;
            this.csptProductName = csptProductName;
            this.minNumber = minNumber;
            this.maxNumber = maxNumber;
            this.pairCount = pairCount;
            this.locationA = locationA;
            this.locationB = locationB;
            this.g3e_fid = g3e_fid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createCableSheathResponse", WrapperNamespace="http://nis.tm.com/", IsWrapped=true)]
    public partial class createCableSheathResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebView.NEPS_NIS.createCSReply @return;
        
        public createCableSheathResponse() {
        }
        
        public createCableSheathResponse(WebView.NEPS_NIS.createCSReply @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dataMatchingUpdate", WrapperNamespace="http://nis.tm.com/", IsWrapped=true)]
    public partial class dataMatchingUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string entityType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nisSystemId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string g3e_fid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string locationTtname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equipmentFrame;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string index;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equpFrameStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string frauPosition;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string frauName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string frauDistance;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equpManrAbbreviation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equpEqumModel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardModel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardSerial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=16)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cabsName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=17)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cabsCastType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=18)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cabsStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=19)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cabsProductName;
        
        public dataMatchingUpdateRequest() {
        }
        
        public dataMatchingUpdateRequest(
                    string entityType, 
                    string nisSystemId, 
                    string g3e_fid, 
                    string locationTtname, 
                    string equipmentFrame, 
                    string index, 
                    string equpFrameStatus, 
                    string frauPosition, 
                    string frauName, 
                    string frauDistance, 
                    string equpManrAbbreviation, 
                    string equpEqumModel, 
                    string cardName, 
                    string cardModel, 
                    string cardStatus, 
                    string cardSerial, 
                    string cabsName, 
                    string cabsCastType, 
                    string cabsStatus, 
                    string cabsProductName) {
            this.entityType = entityType;
            this.nisSystemId = nisSystemId;
            this.g3e_fid = g3e_fid;
            this.locationTtname = locationTtname;
            this.equipmentFrame = equipmentFrame;
            this.index = index;
            this.equpFrameStatus = equpFrameStatus;
            this.frauPosition = frauPosition;
            this.frauName = frauName;
            this.frauDistance = frauDistance;
            this.equpManrAbbreviation = equpManrAbbreviation;
            this.equpEqumModel = equpEqumModel;
            this.cardName = cardName;
            this.cardModel = cardModel;
            this.cardStatus = cardStatus;
            this.cardSerial = cardSerial;
            this.cabsName = cabsName;
            this.cabsCastType = cabsCastType;
            this.cabsStatus = cabsStatus;
            this.cabsProductName = cabsProductName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dataMatchingUpdateResponse", WrapperNamespace="http://nis.tm.com/", IsWrapped=true)]
    public partial class dataMatchingUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebView.NEPS_NIS.commonResponse @return;
        
        public dataMatchingUpdateResponse() {
        }
        
        public dataMatchingUpdateResponse(WebView.NEPS_NIS.commonResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dataMatchingQuery", WrapperNamespace="http://nis.tm.com/", IsWrapped=true)]
    public partial class dataMatchingQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string entityType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string entLocationName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string entFracEqupType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string entIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string entNisId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string g3e_fid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string entCabsId;
        
        public dataMatchingQueryRequest() {
        }
        
        public dataMatchingQueryRequest(string entityType, string entLocationName, string entFracEqupType, string entIndex, string entNisId, string g3e_fid, string entCabsId) {
            this.entityType = entityType;
            this.entLocationName = entLocationName;
            this.entFracEqupType = entFracEqupType;
            this.entIndex = entIndex;
            this.entNisId = entNisId;
            this.g3e_fid = g3e_fid;
            this.entCabsId = entCabsId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dataMatchingQueryResponse", WrapperNamespace="http://nis.tm.com/", IsWrapped=true)]
    public partial class dataMatchingQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebView.NEPS_NIS.dataMatchingQueryReply @return;
        
        public dataMatchingQueryResponse() {
        }
        
        public dataMatchingQueryResponse(WebView.NEPS_NIS.dataMatchingQueryReply @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDPAdresses", WrapperNamespace="http://nis.tm.com/", IsWrapped=true)]
    public partial class updateDPAdressesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fracId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string g3e_fid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dpLocationDetail;
        
        public updateDPAdressesRequest() {
        }
        
        public updateDPAdressesRequest(string fracId, string g3e_fid, string dpLocationDetail) {
            this.fracId = fracId;
            this.g3e_fid = g3e_fid;
            this.dpLocationDetail = dpLocationDetail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDPAdressesResponse", WrapperNamespace="http://nis.tm.com/", IsWrapped=true)]
    public partial class updateDPAdressesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nis.tm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebView.NEPS_NIS.commonResponse @return;
        
        public updateDPAdressesResponse() {
        }
        
        public updateDPAdressesResponse(WebView.NEPS_NIS.commonResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TM_NEPSManagementAPIChannel : WebView.NEPS_NIS.TM_NEPSManagementAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TM_NEPSManagementAPIClient : System.ServiceModel.ClientBase<WebView.NEPS_NIS.TM_NEPSManagementAPI>, WebView.NEPS_NIS.TM_NEPSManagementAPI {
        
        public TM_NEPSManagementAPIClient() {
        }
        
        public TM_NEPSManagementAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TM_NEPSManagementAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TM_NEPSManagementAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TM_NEPSManagementAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebView.NEPS_NIS.createFrameContainersResponse WebView.NEPS_NIS.TM_NEPSManagementAPI.createFrameContainers(WebView.NEPS_NIS.createFrameContainersRequest request) {
            return base.Channel.createFrameContainers(request);
        }
        
        public WebView.NEPS_NIS.createFCReply createFrameContainers(string locnTtname, string franName, string index, string status, string locationDetail, string areaCode, string areaDescription, string areaAreaCode, string areaAretCode, string g3e_fid) {
            WebView.NEPS_NIS.createFrameContainersRequest inValue = new WebView.NEPS_NIS.createFrameContainersRequest();
            inValue.locnTtname = locnTtname;
            inValue.franName = franName;
            inValue.index = index;
            inValue.status = status;
            inValue.locationDetail = locationDetail;
            inValue.areaCode = areaCode;
            inValue.areaDescription = areaDescription;
            inValue.areaAreaCode = areaAreaCode;
            inValue.areaAretCode = areaAretCode;
            inValue.g3e_fid = g3e_fid;
            WebView.NEPS_NIS.createFrameContainersResponse retVal = ((WebView.NEPS_NIS.TM_NEPSManagementAPI)(this)).createFrameContainers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebView.NEPS_NIS.createFrameUnitsResponse WebView.NEPS_NIS.TM_NEPSManagementAPI.createFrameUnits(WebView.NEPS_NIS.createFrameUnitsRequest request) {
            return base.Channel.createFrameUnits(request);
        }
        
        public WebView.NEPS_NIS.createFUReply createFrameUnits(decimal fracId, string frauPosition, string frauName, decimal frauDistance, string fuptManrAbbreaviation, string terminationType, string productType, decimal countPair, string g3e_fid) {
            WebView.NEPS_NIS.createFrameUnitsRequest inValue = new WebView.NEPS_NIS.createFrameUnitsRequest();
            inValue.fracId = fracId;
            inValue.frauPosition = frauPosition;
            inValue.frauName = frauName;
            inValue.frauDistance = frauDistance;
            inValue.fuptManrAbbreaviation = fuptManrAbbreaviation;
            inValue.terminationType = terminationType;
            inValue.productType = productType;
            inValue.countPair = countPair;
            inValue.g3e_fid = g3e_fid;
            WebView.NEPS_NIS.createFrameUnitsResponse retVal = ((WebView.NEPS_NIS.TM_NEPSManagementAPI)(this)).createFrameUnits(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebView.NEPS_NIS.createServiceBoundaryResponse WebView.NEPS_NIS.TM_NEPSManagementAPI.createServiceBoundary(WebView.NEPS_NIS.createServiceBoundaryRequest request) {
            return base.Channel.createServiceBoundary(request);
        }
        
        public WebView.NEPS_NIS.commonResponse createServiceBoundary(string g3e_fid, string frac_id, string field1, string field2, string streetNumber, string streetType, string streetName, string suburb, string city, string statAbbreviation, string poscCode, string country) {
            WebView.NEPS_NIS.createServiceBoundaryRequest inValue = new WebView.NEPS_NIS.createServiceBoundaryRequest();
            inValue.g3e_fid = g3e_fid;
            inValue.frac_id = frac_id;
            inValue.field1 = field1;
            inValue.field2 = field2;
            inValue.streetNumber = streetNumber;
            inValue.streetType = streetType;
            inValue.streetName = streetName;
            inValue.suburb = suburb;
            inValue.city = city;
            inValue.statAbbreviation = statAbbreviation;
            inValue.poscCode = poscCode;
            inValue.country = country;
            WebView.NEPS_NIS.createServiceBoundaryResponse retVal = ((WebView.NEPS_NIS.TM_NEPSManagementAPI)(this)).createServiceBoundary(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebView.NEPS_NIS.createNetworkElementResponse WebView.NEPS_NIS.TM_NEPSManagementAPI.createNetworkElement(WebView.NEPS_NIS.createNetworkElementRequest request) {
            return base.Channel.createNetworkElement(request);
        }
        
        public WebView.NEPS_NIS.createNEReply createNetworkElement(string equpLocnTtname, string equpEqutAbbreviation, string equpIndex, string locnDetail, string areaCode, string areaDescription, string areaAretCode, string areaAreaCode, string equpStatus, string equpManrAbbreviation, string equpEqumModel, string g3e_fid) {
            WebView.NEPS_NIS.createNetworkElementRequest inValue = new WebView.NEPS_NIS.createNetworkElementRequest();
            inValue.equpLocnTtname = equpLocnTtname;
            inValue.equpEqutAbbreviation = equpEqutAbbreviation;
            inValue.equpIndex = equpIndex;
            inValue.locnDetail = locnDetail;
            inValue.areaCode = areaCode;
            inValue.areaDescription = areaDescription;
            inValue.areaAretCode = areaAretCode;
            inValue.areaAreaCode = areaAreaCode;
            inValue.equpStatus = equpStatus;
            inValue.equpManrAbbreviation = equpManrAbbreviation;
            inValue.equpEqumModel = equpEqumModel;
            inValue.g3e_fid = g3e_fid;
            WebView.NEPS_NIS.createNetworkElementResponse retVal = ((WebView.NEPS_NIS.TM_NEPSManagementAPI)(this)).createNetworkElement(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebView.NEPS_NIS.createCardResponse WebView.NEPS_NIS.TM_NEPSManagementAPI.createCard(WebView.NEPS_NIS.createCardRequest request) {
            return base.Channel.createCard(request);
        }
        
        public WebView.NEPS_NIS.createCardReply createCard(string equpId, string cardSlot, string cardName, string cardModel, string cardStatus, string cardSerial, decimal cardCountPort, string portStartNum, string g3e_fid) {
            WebView.NEPS_NIS.createCardRequest inValue = new WebView.NEPS_NIS.createCardRequest();
            inValue.equpId = equpId;
            inValue.cardSlot = cardSlot;
            inValue.cardName = cardName;
            inValue.cardModel = cardModel;
            inValue.cardStatus = cardStatus;
            inValue.cardSerial = cardSerial;
            inValue.cardCountPort = cardCountPort;
            inValue.portStartNum = portStartNum;
            inValue.g3e_fid = g3e_fid;
            WebView.NEPS_NIS.createCardResponse retVal = ((WebView.NEPS_NIS.TM_NEPSManagementAPI)(this)).createCard(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebView.NEPS_NIS.createCableSheathResponse WebView.NEPS_NIS.TM_NEPSManagementAPI.createCableSheath(WebView.NEPS_NIS.createCableSheathRequest request) {
            return base.Channel.createCableSheath(request);
        }
        
        public WebView.NEPS_NIS.createCSReply createCableSheath(string cabsName, string cabsCastType, string cabsStatus, string csptProductName, decimal minNumber, decimal maxNumber, decimal pairCount, string locationA, string locationB, string g3e_fid) {
            WebView.NEPS_NIS.createCableSheathRequest inValue = new WebView.NEPS_NIS.createCableSheathRequest();
            inValue.cabsName = cabsName;
            inValue.cabsCastType = cabsCastType;
            inValue.cabsStatus = cabsStatus;
            inValue.csptProductName = csptProductName;
            inValue.minNumber = minNumber;
            inValue.maxNumber = maxNumber;
            inValue.pairCount = pairCount;
            inValue.locationA = locationA;
            inValue.locationB = locationB;
            inValue.g3e_fid = g3e_fid;
            WebView.NEPS_NIS.createCableSheathResponse retVal = ((WebView.NEPS_NIS.TM_NEPSManagementAPI)(this)).createCableSheath(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebView.NEPS_NIS.dataMatchingUpdateResponse WebView.NEPS_NIS.TM_NEPSManagementAPI.dataMatchingUpdate(WebView.NEPS_NIS.dataMatchingUpdateRequest request) {
            return base.Channel.dataMatchingUpdate(request);
        }
        
        public WebView.NEPS_NIS.commonResponse dataMatchingUpdate(
                    string entityType, 
                    string nisSystemId, 
                    string g3e_fid, 
                    string locationTtname, 
                    string equipmentFrame, 
                    string index, 
                    string equpFrameStatus, 
                    string frauPosition, 
                    string frauName, 
                    string frauDistance, 
                    string equpManrAbbreviation, 
                    string equpEqumModel, 
                    string cardName, 
                    string cardModel, 
                    string cardStatus, 
                    string cardSerial, 
                    string cabsName, 
                    string cabsCastType, 
                    string cabsStatus, 
                    string cabsProductName) {
            WebView.NEPS_NIS.dataMatchingUpdateRequest inValue = new WebView.NEPS_NIS.dataMatchingUpdateRequest();
            inValue.entityType = entityType;
            inValue.nisSystemId = nisSystemId;
            inValue.g3e_fid = g3e_fid;
            inValue.locationTtname = locationTtname;
            inValue.equipmentFrame = equipmentFrame;
            inValue.index = index;
            inValue.equpFrameStatus = equpFrameStatus;
            inValue.frauPosition = frauPosition;
            inValue.frauName = frauName;
            inValue.frauDistance = frauDistance;
            inValue.equpManrAbbreviation = equpManrAbbreviation;
            inValue.equpEqumModel = equpEqumModel;
            inValue.cardName = cardName;
            inValue.cardModel = cardModel;
            inValue.cardStatus = cardStatus;
            inValue.cardSerial = cardSerial;
            inValue.cabsName = cabsName;
            inValue.cabsCastType = cabsCastType;
            inValue.cabsStatus = cabsStatus;
            inValue.cabsProductName = cabsProductName;
            WebView.NEPS_NIS.dataMatchingUpdateResponse retVal = ((WebView.NEPS_NIS.TM_NEPSManagementAPI)(this)).dataMatchingUpdate(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebView.NEPS_NIS.dataMatchingQueryResponse WebView.NEPS_NIS.TM_NEPSManagementAPI.dataMatchingQuery(WebView.NEPS_NIS.dataMatchingQueryRequest request) {
            return base.Channel.dataMatchingQuery(request);
        }
        
        public WebView.NEPS_NIS.dataMatchingQueryReply dataMatchingQuery(string entityType, string entLocationName, string entFracEqupType, string entIndex, string entNisId, string g3e_fid, string entCabsId) {
            WebView.NEPS_NIS.dataMatchingQueryRequest inValue = new WebView.NEPS_NIS.dataMatchingQueryRequest();
            inValue.entityType = entityType;
            inValue.entLocationName = entLocationName;
            inValue.entFracEqupType = entFracEqupType;
            inValue.entIndex = entIndex;
            inValue.entNisId = entNisId;
            inValue.g3e_fid = g3e_fid;
            inValue.entCabsId = entCabsId;
            WebView.NEPS_NIS.dataMatchingQueryResponse retVal = ((WebView.NEPS_NIS.TM_NEPSManagementAPI)(this)).dataMatchingQuery(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebView.NEPS_NIS.updateDPAdressesResponse WebView.NEPS_NIS.TM_NEPSManagementAPI.updateDPAdresses(WebView.NEPS_NIS.updateDPAdressesRequest request) {
            return base.Channel.updateDPAdresses(request);
        }
        
        public WebView.NEPS_NIS.commonResponse updateDPAdresses(string fracId, string g3e_fid, string dpLocationDetail) {
            WebView.NEPS_NIS.updateDPAdressesRequest inValue = new WebView.NEPS_NIS.updateDPAdressesRequest();
            inValue.fracId = fracId;
            inValue.g3e_fid = g3e_fid;
            inValue.dpLocationDetail = dpLocationDetail;
            WebView.NEPS_NIS.updateDPAdressesResponse retVal = ((WebView.NEPS_NIS.TM_NEPSManagementAPI)(this)).updateDPAdresses(inValue);
            return retVal.@return;
        }
    }
}
