//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace WebView
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities_ISP : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities_ISP object using the connection string found in the 'Entities_ISP' section of the application configuration file.
        /// </summary>
        public Entities_ISP() : base("name=Entities_ISP", "Entities_ISP")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities_ISP object.
        /// </summary>
        public Entities_ISP(string connectionString) : base(connectionString, "Entities_ISP")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities_ISP object.
        /// </summary>
        public Entities_ISP(EntityConnection connection) : base(connection, "Entities_ISP")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ISP_NETELEM> ISP_NETELEM
        {
            get
            {
                if ((_ISP_NETELEM == null))
                {
                    _ISP_NETELEM = base.CreateObjectSet<ISP_NETELEM>("ISP_NETELEM");
                }
                return _ISP_NETELEM;
            }
        }
        private ObjectSet<ISP_NETELEM> _ISP_NETELEM;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ISP_NETELEM EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToISP_NETELEM(ISP_NETELEM iSP_NETELEM)
        {
            base.AddObject("ISP_NETELEM", iSP_NETELEM);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="ISP_NETELEM")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ISP_NETELEM : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ISP_NETELEM object.
        /// </summary>
        /// <param name="iSP_TYPE">Initial value of the ISP_TYPE property.</param>
        /// <param name="iSP_ID">Initial value of the ISP_ID property.</param>
        /// <param name="mIN_MATERIAL">Initial value of the MIN_MATERIAL property.</param>
        /// <param name="sCHEME_NAME">Initial value of the SCHEME_NAME property.</param>
        public static ISP_NETELEM CreateISP_NETELEM(global::System.String iSP_TYPE, global::System.String iSP_ID, global::System.String mIN_MATERIAL, global::System.String sCHEME_NAME)
        {
            ISP_NETELEM iSP_NETELEM = new ISP_NETELEM();
            iSP_NETELEM.ISP_TYPE = iSP_TYPE;
            iSP_NETELEM.ISP_ID = iSP_ID;
            iSP_NETELEM.MIN_MATERIAL = mIN_MATERIAL;
            iSP_NETELEM.SCHEME_NAME = sCHEME_NAME;
            return iSP_NETELEM;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ISP_TYPE
        {
            get
            {
                return _ISP_TYPE;
            }
            set
            {
                if (_ISP_TYPE != value)
                {
                    OnISP_TYPEChanging(value);
                    ReportPropertyChanging("ISP_TYPE");
                    _ISP_TYPE = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ISP_TYPE");
                    OnISP_TYPEChanged();
                }
            }
        }
        private global::System.String _ISP_TYPE;
        partial void OnISP_TYPEChanging(global::System.String value);
        partial void OnISP_TYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ISP_ID
        {
            get
            {
                return _ISP_ID;
            }
            set
            {
                if (_ISP_ID != value)
                {
                    OnISP_IDChanging(value);
                    ReportPropertyChanging("ISP_ID");
                    _ISP_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ISP_ID");
                    OnISP_IDChanged();
                }
            }
        }
        private global::System.String _ISP_ID;
        partial void OnISP_IDChanging(global::System.String value);
        partial void OnISP_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MIN_MATERIAL
        {
            get
            {
                return _MIN_MATERIAL;
            }
            set
            {
                if (_MIN_MATERIAL != value)
                {
                    OnMIN_MATERIALChanging(value);
                    ReportPropertyChanging("MIN_MATERIAL");
                    _MIN_MATERIAL = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MIN_MATERIAL");
                    OnMIN_MATERIALChanged();
                }
            }
        }
        private global::System.String _MIN_MATERIAL;
        partial void OnMIN_MATERIALChanging(global::System.String value);
        partial void OnMIN_MATERIALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SCHEME_NAME
        {
            get
            {
                return _SCHEME_NAME;
            }
            set
            {
                if (_SCHEME_NAME != value)
                {
                    OnSCHEME_NAMEChanging(value);
                    ReportPropertyChanging("SCHEME_NAME");
                    _SCHEME_NAME = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SCHEME_NAME");
                    OnSCHEME_NAMEChanged();
                }
            }
        }
        private global::System.String _SCHEME_NAME;
        partial void OnSCHEME_NAMEChanging(global::System.String value);
        partial void OnSCHEME_NAMEChanged();

        #endregion
    
    }

    #endregion
    
}
