//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WebView
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities7 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities7 object using the connection string found in the 'Entities7' section of the application configuration file.
        /// </summary>
        public Entities7() : base("name=Entities7", "Entities7")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities7 object.
        /// </summary>
        public Entities7(string connectionString) : base(connectionString, "Entities7")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities7 object.
        /// </summary>
        public Entities7(EntityConnection connection) : base(connection, "Entities7")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WV_LOAD_PATH_CONSUMER2> WV_LOAD_PATH_CONSUMER2
        {
            get
            {
                if ((_WV_LOAD_PATH_CONSUMER2 == null))
                {
                    _WV_LOAD_PATH_CONSUMER2 = base.CreateObjectSet<WV_LOAD_PATH_CONSUMER2>("WV_LOAD_PATH_CONSUMER2");
                }
                return _WV_LOAD_PATH_CONSUMER2;
            }
        }
        private ObjectSet<WV_LOAD_PATH_CONSUMER2> _WV_LOAD_PATH_CONSUMER2;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WV_LOAD_PATH_CONSUMER_ODP> WV_LOAD_PATH_CONSUMER_ODP
        {
            get
            {
                if ((_WV_LOAD_PATH_CONSUMER_ODP == null))
                {
                    _WV_LOAD_PATH_CONSUMER_ODP = base.CreateObjectSet<WV_LOAD_PATH_CONSUMER_ODP>("WV_LOAD_PATH_CONSUMER_ODP");
                }
                return _WV_LOAD_PATH_CONSUMER_ODP;
            }
        }
        private ObjectSet<WV_LOAD_PATH_CONSUMER_ODP> _WV_LOAD_PATH_CONSUMER_ODP;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VW_MANHOLEDUCT_JOB> VW_MANHOLEDUCT_JOB
        {
            get
            {
                if ((_VW_MANHOLEDUCT_JOB == null))
                {
                    _VW_MANHOLEDUCT_JOB = base.CreateObjectSet<VW_MANHOLEDUCT_JOB>("VW_MANHOLEDUCT_JOB");
                }
                return _VW_MANHOLEDUCT_JOB;
            }
        }
        private ObjectSet<VW_MANHOLEDUCT_JOB> _VW_MANHOLEDUCT_JOB;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WV_LOAD_PATH_CONSUMER2 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWV_LOAD_PATH_CONSUMER2(WV_LOAD_PATH_CONSUMER2 wV_LOAD_PATH_CONSUMER2)
        {
            base.AddObject("WV_LOAD_PATH_CONSUMER2", wV_LOAD_PATH_CONSUMER2);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WV_LOAD_PATH_CONSUMER_ODP EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWV_LOAD_PATH_CONSUMER_ODP(WV_LOAD_PATH_CONSUMER_ODP wV_LOAD_PATH_CONSUMER_ODP)
        {
            base.AddObject("WV_LOAD_PATH_CONSUMER_ODP", wV_LOAD_PATH_CONSUMER_ODP);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VW_MANHOLEDUCT_JOB EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVW_MANHOLEDUCT_JOB(VW_MANHOLEDUCT_JOB vW_MANHOLEDUCT_JOB)
        {
            base.AddObject("VW_MANHOLEDUCT_JOB", vW_MANHOLEDUCT_JOB);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model7", Name="VW_MANHOLEDUCT_JOB")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VW_MANHOLEDUCT_JOB : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VW_MANHOLEDUCT_JOB object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static VW_MANHOLEDUCT_JOB CreateVW_MANHOLEDUCT_JOB(global::System.Int32 id)
        {
            VW_MANHOLEDUCT_JOB vW_MANHOLEDUCT_JOB = new VW_MANHOLEDUCT_JOB();
            vW_MANHOLEDUCT_JOB.ID = id;
            return vW_MANHOLEDUCT_JOB;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JOB_ID
        {
            get
            {
                return _JOB_ID;
            }
            set
            {
                OnJOB_IDChanging(value);
                ReportPropertyChanging("JOB_ID");
                _JOB_ID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("JOB_ID");
                OnJOB_IDChanged();
            }
        }
        private global::System.String _JOB_ID;
        partial void OnJOB_IDChanging(global::System.String value);
        partial void OnJOB_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ASSIGN_ID
        {
            get
            {
                return _ASSIGN_ID;
            }
            set
            {
                OnASSIGN_IDChanging(value);
                ReportPropertyChanging("ASSIGN_ID");
                _ASSIGN_ID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ASSIGN_ID");
                OnASSIGN_IDChanged();
            }
        }
        private global::System.String _ASSIGN_ID;
        partial void OnASSIGN_IDChanging(global::System.String value);
        partial void OnASSIGN_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EXC_ABB
        {
            get
            {
                return _EXC_ABB;
            }
            set
            {
                OnEXC_ABBChanging(value);
                ReportPropertyChanging("EXC_ABB");
                _EXC_ABB = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EXC_ABB");
                OnEXC_ABBChanged();
            }
        }
        private global::System.String _EXC_ABB;
        partial void OnEXC_ABBChanging(global::System.String value);
        partial void OnEXC_ABBChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model7", Name="WV_LOAD_PATH_CONSUMER_ODP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WV_LOAD_PATH_CONSUMER_ODP : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WV_LOAD_PATH_CONSUMER_ODP object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static WV_LOAD_PATH_CONSUMER_ODP CreateWV_LOAD_PATH_CONSUMER_ODP(global::System.String id)
        {
            WV_LOAD_PATH_CONSUMER_ODP wV_LOAD_PATH_CONSUMER_ODP = new WV_LOAD_PATH_CONSUMER_ODP();
            wV_LOAD_PATH_CONSUMER_ODP.ID = id;
            return wV_LOAD_PATH_CONSUMER_ODP;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ANAME
        {
            get
            {
                return _ANAME;
            }
            set
            {
                OnANAMEChanging(value);
                ReportPropertyChanging("ANAME");
                _ANAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ANAME");
                OnANAMEChanged();
            }
        }
        private global::System.String _ANAME;
        partial void OnANAMEChanging(global::System.String value);
        partial void OnANAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ATYPE
        {
            get
            {
                return _ATYPE;
            }
            set
            {
                OnATYPEChanging(value);
                ReportPropertyChanging("ATYPE");
                _ATYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ATYPE");
                OnATYPEChanged();
            }
        }
        private global::System.String _ATYPE;
        partial void OnATYPEChanging(global::System.String value);
        partial void OnATYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ASITE
        {
            get
            {
                return _ASITE;
            }
            set
            {
                OnASITEChanging(value);
                ReportPropertyChanging("ASITE");
                _ASITE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ASITE");
                OnASITEChanged();
            }
        }
        private global::System.String _ASITE;
        partial void OnASITEChanging(global::System.String value);
        partial void OnASITEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACARD2
        {
            get
            {
                return _ACARD2;
            }
            set
            {
                OnACARD2Changing(value);
                ReportPropertyChanging("ACARD2");
                _ACARD2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ACARD2");
                OnACARD2Changed();
            }
        }
        private global::System.String _ACARD2;
        partial void OnACARD2Changing(global::System.String value);
        partial void OnACARD2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String APORT2
        {
            get
            {
                return _APORT2;
            }
            set
            {
                OnAPORT2Changing(value);
                ReportPropertyChanging("APORT2");
                _APORT2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("APORT2");
                OnAPORT2Changed();
            }
        }
        private global::System.String _APORT2;
        partial void OnAPORT2Changing(global::System.String value);
        partial void OnAPORT2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACARD3
        {
            get
            {
                return _ACARD3;
            }
            set
            {
                OnACARD3Changing(value);
                ReportPropertyChanging("ACARD3");
                _ACARD3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ACARD3");
                OnACARD3Changed();
            }
        }
        private global::System.String _ACARD3;
        partial void OnACARD3Changing(global::System.String value);
        partial void OnACARD3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String APORT3
        {
            get
            {
                return _APORT3;
            }
            set
            {
                OnAPORT3Changing(value);
                ReportPropertyChanging("APORT3");
                _APORT3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("APORT3");
                OnAPORT3Changed();
            }
        }
        private global::System.String _APORT3;
        partial void OnAPORT3Changing(global::System.String value);
        partial void OnAPORT3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZNAME
        {
            get
            {
                return _ZNAME;
            }
            set
            {
                OnZNAMEChanging(value);
                ReportPropertyChanging("ZNAME");
                _ZNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZNAME");
                OnZNAMEChanged();
            }
        }
        private global::System.String _ZNAME;
        partial void OnZNAMEChanging(global::System.String value);
        partial void OnZNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZTYPE
        {
            get
            {
                return _ZTYPE;
            }
            set
            {
                OnZTYPEChanging(value);
                ReportPropertyChanging("ZTYPE");
                _ZTYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZTYPE");
                OnZTYPEChanged();
            }
        }
        private global::System.String _ZTYPE;
        partial void OnZTYPEChanging(global::System.String value);
        partial void OnZTYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZSITE
        {
            get
            {
                return _ZSITE;
            }
            set
            {
                OnZSITEChanging(value);
                ReportPropertyChanging("ZSITE");
                _ZSITE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZSITE");
                OnZSITEChanged();
            }
        }
        private global::System.String _ZSITE;
        partial void OnZSITEChanging(global::System.String value);
        partial void OnZSITEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZCARD
        {
            get
            {
                return _ZCARD;
            }
            set
            {
                OnZCARDChanging(value);
                ReportPropertyChanging("ZCARD");
                _ZCARD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZCARD");
                OnZCARDChanged();
            }
        }
        private global::System.String _ZCARD;
        partial void OnZCARDChanging(global::System.String value);
        partial void OnZCARDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZPORT
        {
            get
            {
                return _ZPORT;
            }
            set
            {
                OnZPORTChanging(value);
                ReportPropertyChanging("ZPORT");
                _ZPORT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZPORT");
                OnZPORTChanged();
            }
        }
        private global::System.String _ZPORT;
        partial void OnZPORTChanging(global::System.String value);
        partial void OnZPORTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DPNAME
        {
            get
            {
                return _DPNAME;
            }
            set
            {
                OnDPNAMEChanging(value);
                ReportPropertyChanging("DPNAME");
                _DPNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DPNAME");
                OnDPNAMEChanged();
            }
        }
        private global::System.String _DPNAME;
        partial void OnDPNAMEChanging(global::System.String value);
        partial void OnDPNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DPSITE
        {
            get
            {
                return _DPSITE;
            }
            set
            {
                OnDPSITEChanging(value);
                ReportPropertyChanging("DPSITE");
                _DPSITE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DPSITE");
                OnDPSITEChanged();
            }
        }
        private global::System.String _DPSITE;
        partial void OnDPSITEChanging(global::System.String value);
        partial void OnDPSITEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DPPORT
        {
            get
            {
                return _DPPORT;
            }
            set
            {
                OnDPPORTChanging(value);
                ReportPropertyChanging("DPPORT");
                _DPPORT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DPPORT");
                OnDPPORTChanged();
            }
        }
        private global::System.String _DPPORT;
        partial void OnDPPORTChanging(global::System.String value);
        partial void OnDPPORTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JOBID
        {
            get
            {
                return _JOBID;
            }
            set
            {
                OnJOBIDChanging(value);
                ReportPropertyChanging("JOBID");
                _JOBID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("JOBID");
                OnJOBIDChanged();
            }
        }
        private global::System.String _JOBID;
        partial void OnJOBIDChanging(global::System.String value);
        partial void OnJOBIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PROCESSID
        {
            get
            {
                return _PROCESSID;
            }
            set
            {
                OnPROCESSIDChanging(value);
                ReportPropertyChanging("PROCESSID");
                _PROCESSID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PROCESSID");
                OnPROCESSIDChanged();
            }
        }
        private global::System.String _PROCESSID;
        partial void OnPROCESSIDChanging(global::System.String value);
        partial void OnPROCESSIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PROCESSTIME
        {
            get
            {
                return _PROCESSTIME;
            }
            set
            {
                OnPROCESSTIMEChanging(value);
                ReportPropertyChanging("PROCESSTIME");
                _PROCESSTIME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PROCESSTIME");
                OnPROCESSTIMEChanged();
            }
        }
        private global::System.String _PROCESSTIME;
        partial void OnPROCESSTIMEChanging(global::System.String value);
        partial void OnPROCESSTIMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String REMARKS
        {
            get
            {
                return _REMARKS;
            }
            set
            {
                OnREMARKSChanging(value);
                ReportPropertyChanging("REMARKS");
                _REMARKS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("REMARKS");
                OnREMARKSChanged();
            }
        }
        private global::System.String _REMARKS;
        partial void OnREMARKSChanging(global::System.String value);
        partial void OnREMARKSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACARD4
        {
            get
            {
                return _ACARD4;
            }
            set
            {
                OnACARD4Changing(value);
                ReportPropertyChanging("ACARD4");
                _ACARD4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ACARD4");
                OnACARD4Changed();
            }
        }
        private global::System.String _ACARD4;
        partial void OnACARD4Changing(global::System.String value);
        partial void OnACARD4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String APORT4
        {
            get
            {
                return _APORT4;
            }
            set
            {
                OnAPORT4Changing(value);
                ReportPropertyChanging("APORT4");
                _APORT4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("APORT4");
                OnAPORT4Changed();
            }
        }
        private global::System.String _APORT4;
        partial void OnAPORT4Changing(global::System.String value);
        partial void OnAPORT4Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model7", Name="WV_LOAD_PATH_CONSUMER2")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WV_LOAD_PATH_CONSUMER2 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WV_LOAD_PATH_CONSUMER2 object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static WV_LOAD_PATH_CONSUMER2 CreateWV_LOAD_PATH_CONSUMER2(global::System.String id)
        {
            WV_LOAD_PATH_CONSUMER2 wV_LOAD_PATH_CONSUMER2 = new WV_LOAD_PATH_CONSUMER2();
            wV_LOAD_PATH_CONSUMER2.ID = id;
            return wV_LOAD_PATH_CONSUMER2;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ANAME
        {
            get
            {
                return _ANAME;
            }
            set
            {
                OnANAMEChanging(value);
                ReportPropertyChanging("ANAME");
                _ANAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ANAME");
                OnANAMEChanged();
            }
        }
        private global::System.String _ANAME;
        partial void OnANAMEChanging(global::System.String value);
        partial void OnANAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ATYPE
        {
            get
            {
                return _ATYPE;
            }
            set
            {
                OnATYPEChanging(value);
                ReportPropertyChanging("ATYPE");
                _ATYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ATYPE");
                OnATYPEChanged();
            }
        }
        private global::System.String _ATYPE;
        partial void OnATYPEChanging(global::System.String value);
        partial void OnATYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ASITE
        {
            get
            {
                return _ASITE;
            }
            set
            {
                OnASITEChanging(value);
                ReportPropertyChanging("ASITE");
                _ASITE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ASITE");
                OnASITEChanged();
            }
        }
        private global::System.String _ASITE;
        partial void OnASITEChanging(global::System.String value);
        partial void OnASITEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACARD2
        {
            get
            {
                return _ACARD2;
            }
            set
            {
                OnACARD2Changing(value);
                ReportPropertyChanging("ACARD2");
                _ACARD2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ACARD2");
                OnACARD2Changed();
            }
        }
        private global::System.String _ACARD2;
        partial void OnACARD2Changing(global::System.String value);
        partial void OnACARD2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String APORT2
        {
            get
            {
                return _APORT2;
            }
            set
            {
                OnAPORT2Changing(value);
                ReportPropertyChanging("APORT2");
                _APORT2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("APORT2");
                OnAPORT2Changed();
            }
        }
        private global::System.String _APORT2;
        partial void OnAPORT2Changing(global::System.String value);
        partial void OnAPORT2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACARD3
        {
            get
            {
                return _ACARD3;
            }
            set
            {
                OnACARD3Changing(value);
                ReportPropertyChanging("ACARD3");
                _ACARD3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ACARD3");
                OnACARD3Changed();
            }
        }
        private global::System.String _ACARD3;
        partial void OnACARD3Changing(global::System.String value);
        partial void OnACARD3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String APORT3
        {
            get
            {
                return _APORT3;
            }
            set
            {
                OnAPORT3Changing(value);
                ReportPropertyChanging("APORT3");
                _APORT3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("APORT3");
                OnAPORT3Changed();
            }
        }
        private global::System.String _APORT3;
        partial void OnAPORT3Changing(global::System.String value);
        partial void OnAPORT3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZNAME
        {
            get
            {
                return _ZNAME;
            }
            set
            {
                OnZNAMEChanging(value);
                ReportPropertyChanging("ZNAME");
                _ZNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZNAME");
                OnZNAMEChanged();
            }
        }
        private global::System.String _ZNAME;
        partial void OnZNAMEChanging(global::System.String value);
        partial void OnZNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZTYPE
        {
            get
            {
                return _ZTYPE;
            }
            set
            {
                OnZTYPEChanging(value);
                ReportPropertyChanging("ZTYPE");
                _ZTYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZTYPE");
                OnZTYPEChanged();
            }
        }
        private global::System.String _ZTYPE;
        partial void OnZTYPEChanging(global::System.String value);
        partial void OnZTYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZSITE
        {
            get
            {
                return _ZSITE;
            }
            set
            {
                OnZSITEChanging(value);
                ReportPropertyChanging("ZSITE");
                _ZSITE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZSITE");
                OnZSITEChanged();
            }
        }
        private global::System.String _ZSITE;
        partial void OnZSITEChanging(global::System.String value);
        partial void OnZSITEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZCARD
        {
            get
            {
                return _ZCARD;
            }
            set
            {
                OnZCARDChanging(value);
                ReportPropertyChanging("ZCARD");
                _ZCARD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZCARD");
                OnZCARDChanged();
            }
        }
        private global::System.String _ZCARD;
        partial void OnZCARDChanging(global::System.String value);
        partial void OnZCARDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZPORT
        {
            get
            {
                return _ZPORT;
            }
            set
            {
                OnZPORTChanging(value);
                ReportPropertyChanging("ZPORT");
                _ZPORT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZPORT");
                OnZPORTChanged();
            }
        }
        private global::System.String _ZPORT;
        partial void OnZPORTChanging(global::System.String value);
        partial void OnZPORTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DPNAME
        {
            get
            {
                return _DPNAME;
            }
            set
            {
                OnDPNAMEChanging(value);
                ReportPropertyChanging("DPNAME");
                _DPNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DPNAME");
                OnDPNAMEChanged();
            }
        }
        private global::System.String _DPNAME;
        partial void OnDPNAMEChanging(global::System.String value);
        partial void OnDPNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DPSITE
        {
            get
            {
                return _DPSITE;
            }
            set
            {
                OnDPSITEChanging(value);
                ReportPropertyChanging("DPSITE");
                _DPSITE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DPSITE");
                OnDPSITEChanged();
            }
        }
        private global::System.String _DPSITE;
        partial void OnDPSITEChanging(global::System.String value);
        partial void OnDPSITEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DPPORT
        {
            get
            {
                return _DPPORT;
            }
            set
            {
                OnDPPORTChanging(value);
                ReportPropertyChanging("DPPORT");
                _DPPORT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DPPORT");
                OnDPPORTChanged();
            }
        }
        private global::System.String _DPPORT;
        partial void OnDPPORTChanging(global::System.String value);
        partial void OnDPPORTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JOBID
        {
            get
            {
                return _JOBID;
            }
            set
            {
                OnJOBIDChanging(value);
                ReportPropertyChanging("JOBID");
                _JOBID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("JOBID");
                OnJOBIDChanged();
            }
        }
        private global::System.String _JOBID;
        partial void OnJOBIDChanging(global::System.String value);
        partial void OnJOBIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PROCESSID
        {
            get
            {
                return _PROCESSID;
            }
            set
            {
                OnPROCESSIDChanging(value);
                ReportPropertyChanging("PROCESSID");
                _PROCESSID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PROCESSID");
                OnPROCESSIDChanged();
            }
        }
        private global::System.String _PROCESSID;
        partial void OnPROCESSIDChanging(global::System.String value);
        partial void OnPROCESSIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PROCESSTIME
        {
            get
            {
                return _PROCESSTIME;
            }
            set
            {
                OnPROCESSTIMEChanging(value);
                ReportPropertyChanging("PROCESSTIME");
                _PROCESSTIME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PROCESSTIME");
                OnPROCESSTIMEChanged();
            }
        }
        private global::System.String _PROCESSTIME;
        partial void OnPROCESSTIMEChanging(global::System.String value);
        partial void OnPROCESSTIMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OUTPORTFDC
        {
            get
            {
                return _OUTPORTFDC;
            }
            set
            {
                OnOUTPORTFDCChanging(value);
                ReportPropertyChanging("OUTPORTFDC");
                _OUTPORTFDC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OUTPORTFDC");
                OnOUTPORTFDCChanged();
            }
        }
        private global::System.String _OUTPORTFDC;
        partial void OnOUTPORTFDCChanging(global::System.String value);
        partial void OnOUTPORTFDCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String INPORTFDP
        {
            get
            {
                return _INPORTFDP;
            }
            set
            {
                OnINPORTFDPChanging(value);
                ReportPropertyChanging("INPORTFDP");
                _INPORTFDP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("INPORTFDP");
                OnINPORTFDPChanged();
            }
        }
        private global::System.String _INPORTFDP;
        partial void OnINPORTFDPChanging(global::System.String value);
        partial void OnINPORTFDPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String REMARKS
        {
            get
            {
                return _REMARKS;
            }
            set
            {
                OnREMARKSChanging(value);
                ReportPropertyChanging("REMARKS");
                _REMARKS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("REMARKS");
                OnREMARKSChanged();
            }
        }
        private global::System.String _REMARKS;
        partial void OnREMARKSChanging(global::System.String value);
        partial void OnREMARKSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String APORT4
        {
            get
            {
                return _APORT4;
            }
            set
            {
                OnAPORT4Changing(value);
                ReportPropertyChanging("APORT4");
                _APORT4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("APORT4");
                OnAPORT4Changed();
            }
        }
        private global::System.String _APORT4;
        partial void OnAPORT4Changing(global::System.String value);
        partial void OnAPORT4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACARD4
        {
            get
            {
                return _ACARD4;
            }
            set
            {
                OnACARD4Changing(value);
                ReportPropertyChanging("ACARD4");
                _ACARD4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ACARD4");
                OnACARD4Changed();
            }
        }
        private global::System.String _ACARD4;
        partial void OnACARD4Changing(global::System.String value);
        partial void OnACARD4Changed();

        #endregion

    
    }

    #endregion

    
}
