//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace WebView.NepsLoadSiteService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NEPSLoadSiteBinding", Namespace="http://www.tm.com.my/hsbb/eai/NEPSLoadSite/")]
    public partial class NEPSLoadSiteService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NEPSLoadSiteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NEPSLoadSiteService() {
            this.Url = global::WebView.Properties.Settings.Default.WebView_NepsLoadSiteService_NEPSLoadSiteService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event NEPSLoadSiteCompletedEventHandler NEPSLoadSiteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tm.com.my/hsbb/eai/NEPSLoadSite/",
            RequestElementName = "NEPSLoadSiteRequest",
            RequestNamespace = "http://www.tm.com.my/hsbb/eai/NEPSLoadSite/",
            ResponseElementName = "NepsLoadSiteResponse",
            ResponseNamespace = "http://www.tm.com.my/hsbb/eai/NEPSLoadSite/",
            Use = System.Web.Services.Description.SoapBindingUse.Literal,
            ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
       //// [return : System.Xml.Serialization.XmlRootAttribute("SiteList", Namespace = "", IsNullable = false, ElementName="nep")]
       // [return: System.Xml.Serialization.XmlElementAttribute("SiteList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //[System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        //[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        //[return: System.ServiceModel.MessageParameterAttribute(Name = "SiteList")]
        [return: System.Xml.Serialization.XmlElementAttribute("SiteList", Namespace="http://www.tm.com.my/hsbb/eai/NEPSLoadSite/")]
      
        public NEPSLoadSiteResponseSiteList NEPSLoadSite([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string eventName, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string UserId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] NEPSLoadSiteRequestSetSite SetSite, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] NEPSLoadSiteRequestSiteAddress SiteAddress, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] NEPSLoadSiteRequestSiteDpUDA SiteDpUDA, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out NEPSLoadSiteResponseListAddress ListAddress, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out NEPSLoadSiteResponseListSiteUDA ListSiteUDA, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out NEPSLoadSiteResponseCallstatus Callstatus) {
            object[] results = this.Invoke("NEPSLoadSite", new object[] {
                        eventName,
                        UserId,
                        SetSite,
                        SiteAddress,
                        SiteDpUDA});
           ListAddress = ((NEPSLoadSiteResponseListAddress)(results[1]));
            ListSiteUDA = ((NEPSLoadSiteResponseListSiteUDA)(results[2]));
            Callstatus = ((NEPSLoadSiteResponseCallstatus)(results[3]));
            return ((NEPSLoadSiteResponseSiteList)(results[0]));
        }
        
        /// <remarks/>
        public void NEPSLoadSiteAsync(string eventName, string UserId, NEPSLoadSiteRequestSetSite SetSite, NEPSLoadSiteRequestSiteAddress SiteAddress, NEPSLoadSiteRequestSiteDpUDA SiteDpUDA) {
            this.NEPSLoadSiteAsync(eventName, UserId, SetSite, SiteAddress, SiteDpUDA, null);
        }
        
        /// <remarks/>
        public void NEPSLoadSiteAsync(string eventName, string UserId, NEPSLoadSiteRequestSetSite SetSite, NEPSLoadSiteRequestSiteAddress SiteAddress, NEPSLoadSiteRequestSiteDpUDA SiteDpUDA, object userState) {
            if ((this.NEPSLoadSiteOperationCompleted == null)) {
                this.NEPSLoadSiteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNEPSLoadSiteOperationCompleted);
            }
            this.InvokeAsync("NEPSLoadSite", new object[] {
                        eventName,
                        UserId,
                        SetSite,
                        SiteAddress,
                        SiteDpUDA}, this.NEPSLoadSiteOperationCompleted, userState);
        }
        
        private void OnNEPSLoadSiteOperationCompleted(object arg) {
            if ((this.NEPSLoadSiteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NEPSLoadSiteCompleted(this, new NEPSLoadSiteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tm.com.my/hsbb/eai/NEPSLoadSite/")]
    public partial class NEPSLoadSiteRequestSetSite {
        
        private string siteRegionField;
        
        private string siteStateField;
        
        private string sitePTTField;
        
        private string siteExchangeField;
        
        private string siteNameField;
        
        private string siteDescField;
        
        private string siteTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteRegion {
            get {
                return this.siteRegionField;
            }
            set {
                this.siteRegionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteState {
            get {
                return this.siteStateField;
            }
            set {
                this.siteStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SitePTT {
            get {
                return this.sitePTTField;
            }
            set {
                this.sitePTTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteExchange {
            get {
                return this.siteExchangeField;
            }
            set {
                this.siteExchangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteName {
            get {
                return this.siteNameField;
            }
            set {
                this.siteNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteDesc {
            get {
                return this.siteDescField;
            }
            set {
                this.siteDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteType {
            get {
                return this.siteTypeField;
            }
            set {
                this.siteTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tm.com.my/hsbb/eai/NEPSLoadSite/")]
    public partial class NEPSLoadSiteRequestSiteAddress {
        
        private string siteFloorField;
        
        private string siteNoField;
        
        private string siteBuildingField;
        
        private string addressStreetField;
        
        private string addressCityField;
        
        private string addressStateField;
        
        private string postcodeField;
        
        private string streetTypeField;
        
        private string countyField;
        
        private string countryField;
        
        private string siteCommentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteFloor {
            get {
                return this.siteFloorField;
            }
            set {
                this.siteFloorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteNo {
            get {
                return this.siteNoField;
            }
            set {
                this.siteNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteBuilding {
            get {
                return this.siteBuildingField;
            }
            set {
                this.siteBuildingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressStreet {
            get {
                return this.addressStreetField;
            }
            set {
                this.addressStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressCity {
            get {
                return this.addressCityField;
            }
            set {
                this.addressCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressState {
            get {
                return this.addressStateField;
            }
            set {
                this.addressStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StreetType {
            get {
                return this.streetTypeField;
            }
            set {
                this.streetTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteComments {
            get {
                return this.siteCommentsField;
            }
            set {
                this.siteCommentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tm.com.my/hsbb/eai/NEPSLoadSite/")]
    public partial class NEPSLoadSiteRequestSiteDpUDA {
        
        private string equipmentLocationField;
        
        private string cablingTypeField;
        
        private string copperOwnByTMField;
        
        private string fiberToPremiseExistField;
        
        private string totalServiceBondaryField;
        
        private string accessRestrictionsField;
        
        private string contactField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EquipmentLocation {
            get {
                return this.equipmentLocationField;
            }
            set {
                this.equipmentLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CablingType {
            get {
                return this.cablingTypeField;
            }
            set {
                this.cablingTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CopperOwnByTM {
            get {
                return this.copperOwnByTMField;
            }
            set {
                this.copperOwnByTMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FiberToPremiseExist {
            get {
                return this.fiberToPremiseExistField;
            }
            set {
                this.fiberToPremiseExistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string TotalServiceBondary {
            get {
                return this.totalServiceBondaryField;
            }
            set {
                this.totalServiceBondaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AccessRestrictions {
            get {
                return this.accessRestrictionsField;
            }
            set {
                this.accessRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    ///// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace="http://www.tm.com.my/hsbb/eai/NEPSLoadSite/")]

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    //[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    //[System.ServiceModel.MessageContractAttribute(WrapperName = "NEPSLoadSiteResponseSiteList", WrapperNamespace = "http://www.tm.com.my/hsbb/eai/NEPSLoadSite/", IsWrapped = true)]
    public partial class NEPSLoadSiteResponseSiteList {
        
        private string siteInstIdField;
        
        private string siteNameField;
        
        private string siteDescField;
        
        private string siteTypeField;
        
        private string siteStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string SiteInstId {
            get {
                return this.siteInstIdField;
            }
            set {
                this.siteInstIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteName {
            get {
                return this.siteNameField;
            }
            set {
                this.siteNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteDesc {
            get {
                return this.siteDescField;
            }
            set {
                this.siteDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteType {
            get {
                return this.siteTypeField;
            }
            set {
                this.siteTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteStatus {
            get {
                return this.siteStatusField;
            }
            set {
                this.siteStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace="http://www.tm.com.my/hsbb/eai/NEPSLoadSite/")]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    //[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    //[System.ServiceModel.MessageContractAttribute(WrapperName = "NEPSLoadSiteResponseListAddress", WrapperNamespace = "http://www.tm.com.my/hsbb/eai/NEPSLoadSite/", IsWrapped = true)]
   
    public partial class NEPSLoadSiteResponseListAddress {
        
        private string siteFloorField;
        
        private string siteNoField;
        
        private string siteBuildingField;
        
        private string addressStreetField;
        
        private string addressCityField;
        
        private string addressStateField;
        
        private string postcodeField;
        
        private string streetTypeField;
        
        private string countyField;
        
        private string countryField;
        
        private string siteCommentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteFloor {
            get {
                return this.siteFloorField;
            }
            set {
                this.siteFloorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteNo {
            get {
                return this.siteNoField;
            }
            set {
                this.siteNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteBuilding {
            get {
                return this.siteBuildingField;
            }
            set {
                this.siteBuildingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressStreet {
            get {
                return this.addressStreetField;
            }
            set {
                this.addressStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressCity {
            get {
                return this.addressCityField;
            }
            set {
                this.addressCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressState {
            get {
                return this.addressStateField;
            }
            set {
                this.addressStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StreetType {
            get {
                return this.streetTypeField;
            }
            set {
                this.streetTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteComments {
            get {
                return this.siteCommentsField;
            }
            set {
                this.siteCommentsField = value;
            }
        }
    }
    
    ///// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace="http://www.tm.com.my/hsbb/eai/NEPSLoadSite/")]

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    //[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    //[System.ServiceModel.MessageContractAttribute(WrapperName = "NEPSLoadSiteResponseListSiteUDA", WrapperNamespace = "http://www.tm.com.my/hsbb/eai/NEPSLoadSite/", IsWrapped = true)]
   
    public partial class NEPSLoadSiteResponseListSiteUDA {
        
        private string equipmentLocationField;
        
        private string cablingTypeField;
        
        private string copperOwnByTMField;
        
        private string fiberToPremiseExistField;
        
        private string totalServiceBondaryField;
        
        private string accessRestrictionsField;
        
        private string contactField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EquipmentLocation {
            get {
                return this.equipmentLocationField;
            }
            set {
                this.equipmentLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CablingType {
            get {
                return this.cablingTypeField;
            }
            set {
                this.cablingTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CopperOwnByTM {
            get {
                return this.copperOwnByTMField;
            }
            set {
                this.copperOwnByTMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FiberToPremiseExist {
            get {
                return this.fiberToPremiseExistField;
            }
            set {
                this.fiberToPremiseExistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotalServiceBondary {
            get {
                return this.totalServiceBondaryField;
            }
            set {
                this.totalServiceBondaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AccessRestrictions {
            get {
                return this.accessRestrictionsField;
            }
            set {
                this.accessRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tm.com.my/hsbb/eai/NEPSLoadSite/")]

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    //[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    //[System.ServiceModel.MessageContractAttribute(WrapperName = "NEPSLoadSiteResponseCallstatus", WrapperNamespace = "http://www.tm.com.my/hsbb/eai/NEPSLoadSite/", IsWrapped = true)]
   
   
    public partial class NEPSLoadSiteResponseCallstatus {
        
        private string statusField;
        
        private string messageCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void NEPSLoadSiteCompletedEventHandler(object sender, NEPSLoadSiteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NEPSLoadSiteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NEPSLoadSiteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NEPSLoadSiteResponseSiteList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NEPSLoadSiteResponseSiteList)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public NEPSLoadSiteResponseListAddress ListAddress {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NEPSLoadSiteResponseListAddress)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public NEPSLoadSiteResponseListSiteUDA ListSiteUDA {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NEPSLoadSiteResponseListSiteUDA)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public NEPSLoadSiteResponseCallstatus Callstatus {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NEPSLoadSiteResponseCallstatus)(this.results[3]));
            }
        }
    }
}

#pragma warning restore 1591