//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.BOQNrmService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="nrm-boq", Namespace="http://neps.ag.com/nrm-boq/", ConfigurationName="BOQNrmService.nrmboq")]
    public interface nrmboq {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://neps.ag.com/nrm-boq/generateBOQItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="boqItems")]
        WebView.BOQNrmService.BOQItemList generateBOQItems(out string errorCode, out string errorDesc, string schemeName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://neps.ag.com/nrm-boq/")]
    public partial class BOQItemList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sizeField;
        
        private BOQItem[] boqItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("boqItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public BOQItem[] boqItem {
            get {
                return this.boqItemField;
            }
            set {
                this.boqItemField = value;
                this.RaisePropertyChanged("boqItem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://neps.ag.com/nrm-boq/")]
    public partial class BOQItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeNameField;
        
        private string contractNoField;
        
        private string itemNoField;
        
        private string materialIDField;
        
        private string featureStateField;
        
        private string quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string schemeName {
            get {
                return this.schemeNameField;
            }
            set {
                this.schemeNameField = value;
                this.RaisePropertyChanged("schemeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contractNo {
            get {
                return this.contractNoField;
            }
            set {
                this.contractNoField = value;
                this.RaisePropertyChanged("contractNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string itemNo {
            get {
                return this.itemNoField;
            }
            set {
                this.itemNoField = value;
                this.RaisePropertyChanged("itemNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string materialID {
            get {
                return this.materialIDField;
            }
            set {
                this.materialIDField = value;
                this.RaisePropertyChanged("materialID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string featureState {
            get {
                return this.featureStateField;
            }
            set {
                this.featureStateField = value;
                this.RaisePropertyChanged("featureState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=5)]
        public string quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface nrmboqChannel : WebView.BOQNrmService.nrmboq, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class nrmboqClient : System.ServiceModel.ClientBase<WebView.BOQNrmService.nrmboq>, WebView.BOQNrmService.nrmboq {
        
        public nrmboqClient() {
        }
        
        public nrmboqClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public nrmboqClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public nrmboqClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public nrmboqClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebView.BOQNrmService.BOQItemList generateBOQItems(out string errorCode, out string errorDesc, string schemeName) {
            return base.Channel.generateBOQItems(out errorCode, out errorDesc, schemeName);
        }
    }
}
